# modules/lua/lrun/ai/icp/Makefile

LRUN= ../../../../..

include $(LRUN)/config/make/Config.mak
INSTALL_SUBDIR=$(INSTALL_DIR_LUA)/lrun/ai/icp
LUA_SRC=algorithm.lua distance.lua map.lua transform.lua
SUBDIRS=
include $(LRUN)/config/make/ScriptModule.mak
